# Prediction {#sec-ch2-pred}

@tbl-pred-zigamma-s1 and @tbl-pred-zigamma-s2 summarize the $95\%$ one-step ahead posterior predictive intervals for Scenario 1 and 2, respectively. The overall coverage can obscure important differences in predictive performance. To provide a clearer picture, we decompose the coverage into **below** (i.e., the coverage for values less than or equal to $\epsilon$) and **above** (i.e., the coverage for values greater than $\epsilon$). As shown in these tables, when the zero-inflated probability is low (e.g., $P = 0.1$), the empirical coverage **above** is a more informative metric for assessing predictive performance. As $P$ increases (e.g., $P = 0.5$, $0.7$), the empirical coverage **below** becomes increasingly dominant. 

When $P$ is small, a large proportion of observations fall above $\epsilon$, providing more information to estimate coverage in the upper range. As $P$ increases, more observations concentrate below $\epsilon$, making the coverage in the near-zero range the primary indicator of the overall performance. This shift reflects the change in the underlying data distribution, where increasing $P$ results in a higher proportion of near-zero values. Similiar patterns are observed across all scenarios considered in the simulation study. @fig-pred-zigamma-s1 and @fig-pred-zigamma-s2 convey the same findings but present the empirical coverage as time series for Scenario 1 and 2, respectively. Additional plots for Scenario 3 through 9 are provided in the @sec-appendix-ch2-add-pred. 

```{=latex}
\begin{table}[ht]
\centering
\begin{tabular}{rrrr}
  \hline
 & Coverage & Below & Above \\ 
  \hline
P01Eps01 & 0.9549 & 0.6944 & \textbf{0.9751} \\ 
  P01Eps04 & 0.9148 & 0.3973 & \textbf{0.9786} \\ 
  P05Eps01 & 0.9278 & \textbf{0.9876} & 0.8615 \\ 
  P05Eps04 & 0.9484 & \textbf{0.9681} & 0.9285 \\ 
  P07Eps01 & 0.8677 & \textbf{0.9943} & 0.5726 \\ 
  P07Eps04 & 0.9298 & \textbf{0.9888} & 0.7828 \\ 
   \hline
\end{tabular}
\caption{Empirical coverage of the $95\%$ predictive intervals for ZIGamma Scenario 1 (varying $P$ and $\epsilon$). Each row label indicates the combination of $P$ (zero-inflated probability) and $\epsilon$ (threshold value) used in the simulation. Reported values show overall empirical coverage, with decomposed coverage below and above the threshold.} 
\label{tbl-pred-zigamma-s1}  
\end{table}
```

```{=latex}
\begin{table}[ht]
\centering
\begin{tabular}{rrrr}
  \hline
 & Coverage & Below & Above \\ 
  \hline
P01Eps01 & 0.9479 & 0.6382 & \textbf{0.9734} \\ 
  P01Eps04 & 0.9243 & 0.4038 & \textbf{0.9849} \\ 
  P05Eps01 & 0.9283 & \textbf{0.9972} & 0.8458 \\ 
  P05Eps04 & 0.9519 & \textbf{0.9661} & 0.9374 \\ 
  P07Eps01 & 0.9108 & \textbf{0.9972} & 0.6953 \\ 
  P07Eps04 & 0.9333 & \textbf{0.9885} & 0.7778 \\ 
   \hline
\end{tabular}
\caption{Empirical coverage of the $95\%$ predictive intervals for ZIGamma Scenario 2 (varying $P$ and $\epsilon$). Each row label indicates the combination of $P$ (zero-inflated probability) and $\epsilon$ (threshold value) used in the simulation. Reported values show overall empirical coverage, with decomposed coverage below and above the threshold.}
\label{tbl-pred-zigamma-s2} 
\end{table}
```

![$95\%$ one-step ahead posterior predictive intervals for ZIGamma Scenario 1 (varying $P$ and $\epsilon$). Reported values show overall empirical coverage, with decomposed coverage below and above the threshold shown in parentheses: coverage (coverage for data $\leq \epsilon$, coverage for data $> \epsilon$).](../images/chapter2/pred_zigamma_s1.png){#fig-pred-zigamma-s1}

![$95\%$ one-step ahead posterior predictive intervals for ZIGamma Scenario 2 (varying $P$ and $\epsilon$). Reported values show overall empirical coverage, with decomposed coverage below and above the threshold shown in parentheses: coverage (coverage for data $\leq \epsilon$, coverage for data $> \epsilon$).](../images/chapter2/pred_zigamma_s12.png){#fig-pred-zigamma-s2}

