# Discussion {#sec-ch1-discussion}

In this part of the dissertation, we review a broad class of stationary MTD models and propose a novel copula-based MTD model that builds upon the existing framework. We also present the algorithms and simulation studies, which demonstrate promising results across various scenarios. The advantage of our proposed approach is that, by incorporating copulas into the existing MTD models, the dependence structure and the marginal distribution can be modeled separately, allowing the marginal distribution to be any continuous form. 

In real-world settings, some data exhibit zero-inflation and requires modeling with a mixture model with a point mass at zero. For example, medical costs, insurance claims, precipitation amounts, as well as transportation safety measures such as lane departure severity scores [@mills2013zigamma] and vehicle deceleration during braking [@feng2020zero]. Failure to address these issues undermines model robustness and results. Furthermore, the copula approach may encounter issues when handling a large number of zeros. In such case, the marginal distribution needs to be re-constructed. This motivates the methodological developments introduced in Part II, where we develope a model that addresses the issues of zero-inflation. 

Moreover, a previous study [@hassan2021deep] found comparable predictive performance for disease spread between the probabilistic MTD model and the deep learning long short-term memory (LSTM) network. We aim to compare our approach to this alternative method. This comparative analysis is presented in Part III, where we compare the performance of our proposed MTD models against the LSTMs through simulation studies and real-world data applications. 