# Introduction {#sec-ch1-intro}

Time series data consist of observations measured at regular time intervals. In these data types, observations often exhibit temporal dependence; that is, observations from recent time lags tend to be similar. Examples of time series data are sensor readings, stock prices, sale figures, energy production, weather data, and various other metrics.  

Time series models capture how past values contribute to the current value and use this information to predict future values. In the autoregressive (AR) model with order $p$, for example, each current value depends on all $p$ past values, with fixed, deterministic weights. The mixture transition distribution (MTD) model extends the AR models to accommodate discrete, continuous, and mixed time series, expanding its range of applications. The MTD model models each conditional distribution as a mixture of transition kernels, with random, stochastic weights. 

The first MTD model was developed in 1985 to model high-order Markov chains [@raftery1985model; @raftery1985new], followed by several variant models over the years. Our work builds upon the architecture of the MTD model introduced in 2022 by @zheng2022construction. This model includes various applications, such as the Gaussian MTD, Poisson MTD, negative binomial MTD, and Lomax MTD regression models, extending beyond linear, Gaussian dynamics. However, there are two limitations. First, under this model framework, the transition kernel lacks component-varying parameters. Second, for certain invariant marginal distributions, the transition kernel may either require careful construction or can result in a form that is not explicitly defined or too complex. 

We propose to incorporate copulas into the transition kernels to address the second limitation. Using copulas, dependence structures and marginal distributions can be modeled separately, enabling a choice of copula families that effectively capture data's dependence while allowing flexibility in marginal selection. The proposed copula-based MTD model enables flexible dependence modeling and accommodates any continuous marginals, thereby enhancing modeling capabilities and flexibility. 

The rest of the chapter is organized as follows. We review the MTD model developed by @zheng2022construction in @sec-ch1-background. We present the proposed model in @sec-ch1-prop and provide an overview of the MCMC algorithm for parameter estimation in @sec-ch1-comp. We present the results of various simulations conducted to assess the accuracy and performance of the proposed model in @sec-ch1-simu and discuss the model’s predictive capabilities, including uncertainty quantification, in @sec-ch1-pred. Finally, we conclude with a discussion in @sec-ch1-discussion. @sec-appendix-ch1-pkag provides the instruction for installing the extended `mtd` `R` package. 

  